Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  PublicSubnets:
    Type: String
  VpcId:
    Type: String
  ServiceName:
    Type: String
    Default: "wtxm-bridge-processor"
  MinotariWalletImage:
    Type: AWS::SSM::Parameter::Value<String>
  MinotariWalletImageTag:
    Type: String
  ViewPrivateKey:
    Type: String
  SpendKey:
    Type: String
  InstanceType:
    Type: String
  ECSAMI:
    Description: AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
  NetworkName:
    Type: String
    Default: "esmeralda"
  ProcessorImage:
    Type: AWS::SSM::Parameter::Value<String>
  ProcessorImageTag:
    Type: String
  BackendUrl:
    Type: AWS::SSM::Parameter::Value<String>
  SafeAddress:
    Type: AWS::SSM::Parameter::Value<String>
  WxtmAddress:
    Type: AWS::SSM::Parameter::Value<String>
  KmsKeyId:
    Type: AWS::SSM::Parameter::Value<String>
  EthRpcUrl:
    Type: String
  OperationMode:
    Type: String
    AllowedValues:
      - proposer
      - finalizer

Mappings:
  EC2InstanceConnectMap:
    "eu-north-1":
      SourcePrefixListId: "pl-0bd77a95ba8e317a6"
    "eu-central-1":
      SourcePrefixListId: "pl-03384955215625250"

Resources:
  ProcessorTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Policies:
        - PolicyName: AccessEFS
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:DescribeMountTargets
                  - elasticfilesystem:DescribeFileSystems
                Resource: "*"
        - PolicyName: ExecuteCommadn
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
        - PolicyName: KmsKeyAccess
          PolicyDocument:
            Statement:
                - Effect: Allow
                  Action:
                    - kms:Sign
                    - kms:Decrypt
                    - kms:GenerateDataKey
                    - kms:GetPublicKey
                  Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}

  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Action:
                - ecs:CreateCluster
                - ecs:DeregisterContainerInstance
                - ecs:DiscoverPollEndpoint
                - ecs:Poll
                - ecs:RegisterContainerInstance
                - ecs:StartTelemetrySession
                - ecs:Submit*
                - ecr:BatchCheckLayerAvailability
                - ecr:BatchGetImage
                - ecr:GetDownloadUrlForLayer
                - ecr:GetAuthorizationToken
                - ec2:DescribeInstanceStatus
                - ec2:AssociateAddress
                - logs:CreateLogStream
                - logs:CreateLogGroup
                - logs:PutLogEvents
                - logs:CreateLogStream
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
                - ec2:AttachVolume
                - ec2:CreateVolume
                - ec2:CreateSnapshot
                - ec2:CreateTags
                - ec2:DeleteVolume
                - ec2:DeleteSnapshot
                - ec2:DescribeAvailabilityZones
                - ec2:DescribeInstances
                - ec2:DescribeVolumes
                - ec2:DescribeVolumeAttribute
                - ec2:DescribeVolumeStatus
                - ec2:DescribeSnapshots
                - ec2:CopySnapshot
                - ec2:DescribeSnapshotAttribute
                - ec2:DetachVolume
                - ec2:ModifySnapshotAttribute
                - ec2:ModifyVolumeAttribute
                - ec2:DescribeTags
              Resource: "*"

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref ECSRole

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - !Select
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt ECSLaunchTemplate.LatestVersionNumber
      MinSize: "0"
      MaxSize: "1"
      DesiredCapacity: "1"
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
          PropagateAtLaunch: true

  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref ECSAMI
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !GetAtt ContainerSecurityGroup.GroupId
        IamInstanceProfile:
          Arn: !GetAtt ECSInstanceProfile.Arn
        UserData:
          "Fn::Base64": !Sub |
            #!/bin/bash
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource ECSLaunchTemplate
            docker plugin install rexray/ebs REXRAY_PREEMPT=true EBS_REGION=${AWS::Region} --grant-all-permissions

    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              ecs-init: []
              awslogs: []
              ec2-instance-connect: []
          commands:
            01_add_instance_to_cluster:
              command: !Sub echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
              awslogsd:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/awslogs/awslogs.conf
                  - /etc/awslogs/awscli.conf
          files:
            "/etc/cfn/cfn-hup.conf":
              mode: "000400"
              owner: root
              group: root
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.ECSLaunchTemplate.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource ECSLaunchConfiguration
            "/etc/awslogs/awscli.conf":
              content: !Sub |
                [plugins]
                cwlogs = cwlogs
                [default]
                region = ${AWS::Region}
            "/etc/awslogs/awslogs.conf":
              content: !Sub |
                [/var/tari/wallet/${NetworkName}/log/wallet/base_layer.log]
                file = /var/tari/wallet/${NetworkName}/log/wallet/base_layer.log
                log_group_name = ${LogGroup}
                log_stream_name = {instance_id}/var/tari/wallet/${NetworkName}/log/wallet/base_layer.log



  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName

  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 7

  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
     VpcId: !Ref VpcId
     GroupDescription: ECS Containers Security Group
     SecurityGroupIngress:
       -
         SourcePrefixListId: !FindInMap [EC2InstanceConnectMap, !Ref AWS::Region, SourcePrefixListId]
         FromPort: 22
         ToPort: 22
         IpProtocol: tcp


  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: bridge
      Cpu: 1024
      Memory: 1536
      TaskRoleArn: !GetAtt ProcessorTaskRole.Arn
      ContainerDefinitions:
        - Image: !Sub ${MinotariWalletImage}:${MinotariWalletImageTag}
          Name: minotari-console-wallet
          User: tari
          LinuxParameters:
            InitProcessEnabled: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: minotari-console-wallet
          # EntryPoint:
          #   - sleep
          # Command:
          #   - infinity
          Command:
            - -p base_node.mining_enabled=false
            - --grpc-enabled
            - --grpc-address /ip4/0.0.0.0/tcp/44871
            - --non-interactive-mode
          Environment:
            - Name: MINOTARI_WALLET_PASSWORD
              Value: Ohngie7daeyu
            - Name: MINOTARI_WALLET_VIEW_PRIVATE_KEY
              Value: !Ref ViewPrivateKey
            - Name: MINOTARI_WALLET_SPEND_KEY
              Value: !Ref SpendKey
          MountPoints:
            - ContainerPath: /var/tari/wallet
              SourceVolume: wallet-data
          PortMappings:
            - ContainerPort: 44871
              HostPort: 44871
              Protocol: tcp
        - Image: !Sub ${ProcessorImage}:${ProcessorImageTag}
          Name: wxtm-bridge-processor
          Links:
            - minotari-console-wallet
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: wxtm-bridge-processor
          Environment:
            - Name: ENVIRONMENT
              Value: !Ref Environment
            - Name: MINOTARI_WALLET_HOST
              Value: minotari-console-wallet
            - Name: WXTM_BRIDGE_BACKEND_URL
              Value: !Ref BackendUrl
            - Name: SAFE_ADDRESS
              Value: !Ref SafeAddress
            - Name: WXTM_ADDRESS
              Value: !Ref WxtmAddress
            - Name: KMS_KEY_ID
              Value: !Ref KmsKeyId
            - Name: ETH_RPC_URL
              Value: !Ref EthRpcUrl
            - Name: OPERATION_MODE
              Value: !Ref OperationMode
            - Name: AWS_REGION
              Value: !Ref AWS::Region


      Volumes:
        - Name: wallet-data
          DockerVolumeConfiguration:
            Autoprovision: true
            Scope: shared
            Driver: rexray/ebs
            DriverOpts:
              volumetype: gp2
              size: "2"
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref AWS::StackName
      TaskDefinition: !Ref TaskDefinition
      Cluster: !Ref ECSCluster
      SchedulingStrategy: DAEMON
