AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
  LambdaSecurityGroupId:
    Type: String
  PrivateSubnetsIds:
    Type: String
  DbSecretArn:
    Type: String
  DbHost:
    Type: String
  CertificateArn:
    Type: String

Resources:
  LambdaSecurityGroupParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /multisig/${Environment}/security-group/lambda
      Type: String
      Value: !Ref LambdaSecurityGroupId
      Description: Security group ID for Lambda functions

  PrivateSubnetsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /multisig/${Environment}/vpc/private-subnets
      Type: String
      Value: !Ref PrivateSubnetsIds
      Description: Comma-separated list of private subnet IDs

  DbSecretParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /multisig/${Environment}/database/secret-arn
      Type: String
      Value: !Ref DbSecretArn
      Description: ARN of the database secrets in Secrets Manager

  DbHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /multisig/${Environment}/database/host
      Type: String
      Value: !Ref DbHost
      Description: Database host endpoint

  CertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /multisig/${Environment}/certificate-arn
      Type: String
      Value: !Ref CertificateArn
      Description: ARN of the SSL certificate
